#!/usr/bin/env bash

DEBUG='true'

current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $current_dir/lib/tui
source $current_dir/lib/utils
source $current_dir/lib/cards
source $current_dir/lib/array

ROWS=0
COLS=0

#setup system
goto_tab
clear_screen
move_cursor

get_size ROWS COLS

get_term_size() {
 deblog 'get_term_size called'
 get_size ROWS COLS
}

cleanUp() {
	return_tab
	show_cursor
}

# TRAPS
trap 'get_term_size' WINCH
trap cleanUp exit 


hide_cursor

echo "$ROWS $COLS"


# STATE
HP=20
ROOM=()
DECK=()
ELEMENT_X=0
POTION_USED_THIS_TURN=false
SKIPPED_PREV_ROOM=false
EQUIPPED_WEAPON=0

# INIT
create_deck DECK
_ROOM_SIZE_=4

generateRoom() {
 local currentRoomSize=${#ROOM[@]}
 local turnSkip=${1:-false}

 if [[ $turnSkip == true ]]; then
 	 splice DECK 0 4 ROOM
 else
	 local diff=$((_ROOM_SIZE_ - currentRoomSize))
   local justDrawn=()
	 splice DECK 0 $diff justDrawn
	 ROOM=("${justDrawn[@]}" "${ROOM[@]}")
 fi
}

generateRoom

drawLoop() {
	clear_screen
	move_cursor
	local currentIndex=0
	local isSelected=false
	
	# ROOM
	for card in "${ROOM[@]}"; do
		isSelected=$(( currentIndex == ELEMENT_X ))
		interpolateCard "$card" "$isSelected"
		printf '  '
		(( currentIndex++ ))
	done

	# health
	printf '[ %s\u2695 ]' $HP
}

strategy() {
	local seed=$1
	local value=$2

	case $seed in
		1|2) (( HP -= value - EQUIPPED_WEAPON ));;
		3) (( HP += value ));;
		4) EQUIPPED_WEAPON=$value;;
	esac
}

selectedCardStrategy() {
	local pick=${ROOM[ELEMENT_X]}
	local value
	local seed
	local pickedIdx=$(findIndex ROOM $pick)
	splice ROOM $pickedIdx 1

	IFS='_' read -r value seed <<< "$pick"

  strategy "$seed" "$value"
}

skipRoom() {
 if [[ $SKIPPED_PREV_ROOM == false ]]; then
	 generateRoom true
	 SKIPPED_PREV_ROOM=true
 fi
}

handleKeys() {
 local input=$1

 case $input in
	 a) (( ELEMENT_X = (ELEMENT_X - 1 + ${#ROOM[@]} ) % ${#ROOM[@]}  ));;
	 d) (( ELEMENT_X = (ELEMENT_X + 1) % ${#ROOM[@]}  ));;
	 e) selectedCardStrategy $input;;
	 n) skipRoom;;
	esac
}

main() {
 local inputK=$1
 handleKeys "$inputK"
 drawLoop
}


drawLoop

# Main loop reading keys
while true; do
	read -rsn1 key
	if [[ $key == $'\e' ]]; then
			read -rsn2 rest
			key+="$rest"
	fi
	main $key
done



