#!/usr/bin/env bash

createDeck() {
 local -n deckRef=$1
 # creating Club & spades [monsters]
 deckRef+=($(echo {1..14}_{1..2}))
 # creating hearts & diamonds [ potions & weapons ]
 deckRef+=($(echo {1..9}_{3..4}))

  local _cdi=0
  for ((_cdi=${#deckRef[@]}-1; _cdi>0; _cdi--)); do
    local j=$(($RANDOM % (_cdi+1)))
    local tmp="${deckRef[$_cdi]}"
    deckRef[$_cdi]="${deckRef[$j]}"
    deckRef[$j]="$tmp"
  done
 

 deblog "created deck of l: ${#deckRef[@]}"
}

interpolateValue() {
 local value=$1

 case $value in
	 11) printf 'J';;
         12) printf 'Q';;
	 13) printf 'K';;
	 14) printf 'A';;
	 *) printf $value;;
 esac
}

interpolateSeed() {
 local seed=$1

 case $seed in
	 # spade MONSTER
	 1) printf '\u2660';;
	 # club MONSTER
	 2) printf '\u2663';;
	 # hearth POTION
	 3) printf '\u2665';;
	 #diamonds WEAPON
	 4) printf '\u2666';;
 esac
}

drawCard() {
  local value=$1
  local seed=$2
  local startingColumn=$3
  local startingRow=$4
  local interpolatedSeed=$(interpolateSeed $seed)
  local interpolatedValue=$(interpolateValue $value)
  if (( value == 10)); then 
    local valueLine="│ $interpolatedValue  │"
  else
    local valueLine="│ $interpolatedValue   │"
  fi

  local lines=(
  "╭─────╮"
  "│ $interpolatedSeed   │"
 "$valueLine"
  "╰─────╯"
  )
  
  drawAtPosition "$startingRow" "$startingColumn" lines
}

drawDeck() {
  local value=$1
  local startingColumn=$2
  local startingRow=$3
  
  if (( value > 9)); then 
    local numberOfCards="││$value   │"
  else
    local numberOfCards="││$value  │"
  fi

  local lines=(
  "╭╭─────╮"
  "││     │"
 "$numberOfCards"
  "╰╰─────╯"
  )
  
  drawAtPosition "$startingRow" "$startingColumn" lines
}



interpolateCard() {
 local card=$1
 local selected=${2:-0}
 local startingColumn=$3
 local startingRow=${4:-0}

 IFS='_' read -r value seed <<< "$card"
 local content
 content=$(drawCard "$value" "$seed" "$startingColumn" "$startingRow")

 if (( selected )); then
   drawInverted "$content"
 else 
   printf '%b' "$content"
 fi
}
