#!/usr/bin/env bash

drawAtPosition() {
 local startingRow=${1:-0}
 local startingColumn=${2:-0}

 local -n _localCtn=$3

 local heightOfContent=${#_localCtn[@]}

  local _dai=0
  for ((_dai=0;_dai<$heightOfContent;_dai++)); do
    local termCord=$(($startingRow + $_dai + 1))
    moveCursor "$termCord" "$startingColumn"
    printf '%b' "${_localCtn[_dai]}"
  done
}
