#!/usr/bin/env bash

ESCAPE_SEQ='\e['

interpolate() {
	local command=$1
	printf '%b' "$ESCAPE_SEQ$command"
}

showCursor() {
	interpolate '?25h'	
}

hideCursor() {
	interpolate '?25l'
}

gotoTab() {
	interpolate '?1049h'
}

returnTab() {
	interpolate '?1049l'
}

getSize() {
  declare -n _rowsRef=$1
  declare -n _columnsRef=$2

  read -r _rowsRef _columnsRef < <(stty size)
}

clearScreen() {
  interpolate '2J'	
}

moveCursor() {
 local x=${1:-0}
 local y=${2:-0}

 interpolate "$x;${y}H"
}

drawInverted() {
 local content=$1
 printf '\e[7m%b\e[0m' "$content"
}


drawTitle() {
  local startingRow=${1:-0}
  local startingCol=${2:-0}

  titleRows=(
    '  ____  _                           _          _  ' \
    ' / ___|| |__   ___  _   _ _ __   __| |_ __ ___| | ' \
    " \___ \| '_ \ / _ \| | | | '_ \ / _\` | '__/ _ \ | " \
    '  ___) | | | | (_) | |_| | | | | (_| | | |  __/ | ' \
    ' |____/|_| |_|\___/ \__,_|_| |_|\__,_|_|  \___|_| '
  )

  drawAtPosition "$startingRow" "$startingCol" titleRows 
  local titleHeight=${#titleRows[@]}
  moveCursor $(($startingRow+$titleHeight)) 0
  printf "press P to play"
}
