#!/usr/bin/env bash

ESCAPE_SEQ='\e['

interpolate() {
	local command=$1
	printf '%b' "$ESCAPE_SEQ$command"
}

showCursor() {
	interpolate '?25h'	
}

hideCursor() {
	interpolate '?25l'
}

gotoTab() {
	interpolate '?1049h'
}

returnTab() {
	interpolate '?1049l'
}

getSize() {
  declare -n _rowsRef=$1
  declare -n _columnsRef=$2

  read -r _rowsRef _columnsRef < <(stty size)
}

clearScreen() {
  interpolate '2J'	
}

moveCursor() {
 local x=${1:-0}
 local y=${2:-0}

 interpolate "$x;${y}H"
}

drawInverted() {
 local content=$1
 printf '\e[7m%b\e[0m' "$content"
}
