#!/usr/bin/env bash


deblog() {
 if [[ $DEBUG == 'true' ]]; then
	 echo "<debug> $@"
 fi
}

errorMessage() {
	local message=$1

	echo "$1" 1>&2
	exit 1
}

checkVersion(){
	declare -n test || errorMessage "Bash 4.3+ is required"
}

checkSize() {
	$(($ROWS >= 24 && $COLS >= 80)) || errorMessage "24x80 is the minimum size to render the ui"
}

max() {
 local toTest=$1
 local MAX=$2

 echo $(( $toTest > $MAX ?  $MAX : $toTest ))
}

min() {
 local a=$1
 local b=$2

 echo $(( a < b ? a : b ))
}

clampFloor() {
 local value=$1
 local floor=$2

 echo $(( value < floor ? floor : value ))
}
